### ISSUE TITLE
Poisson likelihood evaluated with wrong formula

### ISSUE THREAD

**Issue by casparschloesser** [nadrino/gundam#175]
The function to compute the Poisson likelihood `PoissonLLH::eval` inside `src/FitSamples/src/JointProbability.cpp` is using a formula which employs the Gamma function (likely to compute a factorial). However, since we are actually computing a likelihood ratio, these factorials cancel out and there is no need for a Gamma function.

The current implementation returns a nonzero chi2_stat for Asimov fits, when the number of "MC" and "data" events is identical. It should be changed back to this:
[https://github.com/nadrino/gundam/blob/78bf753189f6bb5155c0abb79219b06002146155/src/Utils/include/Likelihoods.hh](https://github.com/nadrino/gundam/blob/78bf753189f6bb5155c0abb79219b06002146155/src/Utils/include/Likelihoods.hh)

**Comment by casparschloesser** [comment]
This commit should fix it: [https://github.com/nadrino/gundam/commit/1fad721172bebaa7543b2a2679b78d4b343de315](https://github.com/nadrino/gundam/commit/1fad721172bebaa7543b2a2679b78d4b343de315)

**Comment by nadrino** [comment]
Seems fine to me! Any other checks required before closing the issue? :)

**Comment by riccioc** [comment]
I don't know if my comment to the commit where the bug was fixed is visible, but the formula returns 2*LLH-ratio instead of -2*LLH-ratio. The correct formula should be:

return -2.0 * (predVal - dataVal + dataVal * TMath::Log(dataVal / predVal)); 

Also there should be an expectation for the case when there are 0 event in MC, since it appears in the ratio dataVal / predVal.

**Comment by casparschloesser** [comment]
Actually, even though the function is called `PoissonLLH`, it is really supposed to return the chi2_stat value which should be equal to the expression without the minus. But a special case of 0 events in MC should definitely be added, I will do it soon.

**Comment by casparschloesser** [comment]
With this commit it should all be implemented correctly: https://github.com/nadrino/gundam/commit/a918f76f338b0d0eea8c4c05ede92c805090b5f0

I will close the issue
