### ISSUE TITLE
Normalization parameter in xsec calculation

### ISSUE THREAD

**Issue by XingyuZhao1995** [nadrino/gundam#411]
In `gundamCalcXsec.cpp` line 410:
```
      if     ( GenericToolbox::Json::doKeyExist( config_, "meanValue" ) ){
        normParameter.first  = GenericToolbox::Json::fetchValue<double>(config_, "meanValue");
        normParameter.second = GenericToolbox::Json::fetchValue(config_, "stdDev", 0);
        LogInfo << "mean ± sigma = " << normParameter.first << " ± " << normParameter.second;
      }
```
The `stdDev` variable does not have `double` conversion.

**Comment by nadrino** [comment]
Thank you very much @XingyuZhao1995 ! I've fixed the issue of every instance of the code. It seems that this bug was also present in `minDialResponse` as well for instance.

Associated PR: https://github.com/gundam-organization/gundam/pull/412
